export { normalizeComponent } from './lib/normalize'
export { hookProps } from './lib/props.js'
export { render } from './lib/render.js'
export { mount } from './lib/mount.js'
export { router } from './lib/router.js'
export { link } from './components/link.js'
export { key } from './components/key.js'
export { template } from './components/template.js'
