export { normalizeComponent } from './normalize'
export { processComponent } from './process'
export { hookProps } from './props'
export { render } from './render'
export { mount } from './mount'
export { router } from './router'
