export { normalizeComponent } from './normalize.js'
export { processComponent } from './process.js'
export { hookProps, hookCachedProps } from './props.js'
export { render } from './render.js'
export { mount } from './mount.js'
export { router } from './router.js'
